# Generated by Django 3.2.25 on 2025-03-05 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='details',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='name',
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AddField(
            model_name='application',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_name',
            field=models.CharField(default='Unknown Name', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default='No phone provided', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='quote_number',
            field=models.CharField(default='No quote# provided', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='contact_name',
            field=models.CharField(default='Unknown Name', max_length=255),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='phone_number',
            field=models.CharField(default='No phone provided', max_length=50),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quote_number',
            field=models.CharField(default='No quote# provided', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
