# Generated by Django 3.2.25 on 2025-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20250305_0749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='address',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='company_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='contact_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone_number',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='quote_number',
            field=models.CharField(default=' ', max_length=50, unique=True),
        ),
    ]
