# Generated by Django 3.2.25 on 2025-04-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20250403_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='quote_number',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='website',
        ),
    ]
