# Generated by Django 3.2.25 on 2025-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20250404_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='address',
            field=models.CharField(null=True, blank=True, max_length=255),
        ),
    ]
