# Generated by Django 3.2.25 on 2025-04-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20250411_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
