# Generated by Django 3.2.25 on 2025-04-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20250404_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type_of_work',
            field=models.CharField(blank=True, choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('roofing', 'Roofing')], default='electrical', max_length=50, null=True),
        ),
    ]
