# Generated by Django 3.2.25 on 2025-04-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_type_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type_of_work',
            field=models.CharField(blank=True, choices=[('flooring', 'Flooring'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('roofing', 'Roofing')], default='flooring', max_length=50, null=True),
        ),
    ]
