# Generated by Django 3.2.25 on 2025-04-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_type_of_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='type_of_work',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.typeofproject'),
        ),
    ]
