# Generated by Django 3.2.25 on 2025-04-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_typeofproject_type_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproject',
            name='type_of_work',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
