# Generated by Django 3.2.25 on 2025-04-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20250409_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproject',
            name='type_of_work',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
