# Generated by Django 3.2.25 on 2025-04-09 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_typeofproject_type_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.typeofproject'),
        ),
        migrations.AlterField(
            model_name='typeofproject',
            name='type_of_work',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
