# Generated by Django 3.2.25 on 2025-04-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_typeofproject_type_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproject',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
