# Generated by Django 3.2.25 on 2025-04-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_typeofproject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
