# Generated by Django 3.2.25 on 2025-04-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_typeofproject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproject',
            name='type_of_work',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
