# Generated by Django 3.2.25 on 2025-03-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
