# Generated by Django 3.2.25 on 2025-04-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20250301_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
